[workspace]
resolver = "2"

members = [
    "block_party",
    "staking_party",
    "shielding_party",
    "shielding_reward_party"
]

[workspace.package]
authors = ["Heliax AG <hello@heliax.dev>"]
edition = "2021"
license = "GPL-3.0"
version = "0.1.0"

[workspace.dependencies]
namada_tx_prelude = { git = "https://github.com/anoma/namada", branch = "fraccaman/multitoken-allow-governance-changes" }
namada_proof_of_stake = { git = "https://github.com/anoma/namada", branch = "fraccaman/multitoken-allow-governance-changes" }
namada_core = { git = "https://github.com/anoma/namada", branch = "fraccaman/multitoken-allow-governance-changes" }
wee_alloc = "0.4.5"
getrandom = { version = "0.2", features = ["custom"] }
lazy_static = "1.4.0"

[profile.release]
lto = true
panic = "abort"
opt-level = 'z'
strip = "debuginfo"