name: Earthly +build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GIT_LFS_SKIP_SMUDGE: 1
      REGISTRY_URL: ghcr.io
      FORCE_COLOR: 1
      EARTHLY_TOKEN: ${{ secrets.EARTHLY_TOKEN }}

    permissions:
      contents: read
      packages: write
      actions: read

    steps:
    - uses: earthly/actions-setup@v1
      with:
        version: v0.8.0
    - uses: actions/checkout@v4
    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Run Build (pr)
      if: ${{ github.event_name == 'pull_request' }}
      run: earthly --org heliax --sat namada-governance-upgrades --ci +build
    - name: Run build (main)
      if: ${{ github.ref == 'refs/heads/main' }}
      run: earthly --org heliax --sat namada-governance-upgrades --ci --push +build