name: Earthly +build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

permissions:
  contents: read
  packages: write
  actions: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GIT_LFS_SKIP_SMUDGE: 1
      REGISTRY_URL: ghcr.io
      FORCE_COLOR: 1

    steps:
    - uses: earthly/actions-setup@v1
      with:
        version: "latest"
    - uses: actions/checkout@v4
    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build WASM
      run: earthly +build
    - name: Upload WASM
      uses: actions/upload-artifact@v4
      with:
        name: wasm-${{ github.sha }}
        path: artifacts/